name: personal_profile_card_app
description: A Flutter app to show personal profile in card format.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.20.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  image_picker: ^0.8.7+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
